### ISSUE TITLE
Files no longer detected

### ISSUE THREAD

**Issue by v-fox** [maazl/easytag#3] opened 2024-07-16 13:59 UTC
I've updated from 2.4.3+255\~git20240424.426dead to 2.4.3+272\~git20240517.47a896e and all files became ignored, as if they don't exist, without any errors in logs or terminal. Had to revert.

**Comment by maazl** [comment] 2024-07-16 15:21
Need a scenario to reproduce.
- Which files are no longer recognized? A minimal example file?
- Top level or in subfolder? Are subfolder scans enabled?
- Which platform?

**Comment by v-fox** [comment] 2024-07-17 00:46
> Need a scenario to reproduce.
> 
>     * Which files are no longer recognized? A minimal example file?

All of them everywhere. All file-types in all directories with all kinds of names.

>     * Top level or in subfolder? Are subfolder scans enabled?

Subfolder scans ("interface -> browse subdirectories", I assume) are **not** enabled. Neither is "show hidden directories".

>     * Which platform?

[openSUSE Tumbleweed](https://build.opensuse.org/package/show/home:X0F:branches:multimedia/easytag).

**Comment by v-fox** [comment] 2024-07-20 11:35
> Sorry, I cannot reproduce this. Neither with revision [47a896e](https://github.com/maazl/easytag/commit/47a896e12b3d2732c9b7d1119d81c85e53f9a0f9) 2024-05-17 nor with revision [266dd9a](https://github.com/maazl/easytag/commit/266dd9a4de27a3a8dd418e8b6d828c6d728fc07f) 2024-06-16, a slightly newer one. Did you accidentally disable "Load on startup"?

Nope, that first option in "Interface" was always enabled. Besides, just reverting to older version with the same config made it work again.

> The magic happens in function ET_Get_File_Description. This selects the appropriate handler for each file. If none is found a dummy entry is returned and the file is skipped.
> Maybe some wired things happen on your platform that prevents registration and ETFileDescription is empty. I'm just guessing. Can you debug this somehow?

It really goes over my head. And I'm not sure what you mean exactly by "platform". Isn't it based on GTK3 which pretty much abandoned for years and should be the same everywhere?
Not sure how to debug, crashing would be simple but here it presents itself as if it's normal.

> It could be a static initialization sequence issue. Please could you try whether applying the following patch to the current master branch fixes the issue?

Tried out 2.4.3+275\~git20240717.c26572d with the patch and it seems to work now. Thanks!
I'll let you close it.

**Comment by maazl** [comment] 2024-07-20 12:15
I just discussed the issue in the C++ group. It turned out the self registering classes were always a grey area of the standard and newer compilers may no longer support it. But if this is the reason the applied patch shouldn't fix the issue either. - puzzled
However, I committed the change since it helps for now.

**Closed by maazl** 2024-07-20 12:15 UTC
